# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: better_radar 0.0.0 ruby lib

Gem::Specification.new do |s|
  s.name = "better_radar"
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Dan Garland"]
  s.date = "2015-08-19"
  s.description = "SAX Parser that allows you to respond to information in the BetRadar XML feed"
  s.email = "dan@dangarland.co.uk"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "fixtures/vcr_cassettes/fixtures_feed.yml",
    "lib/better_radar.rb",
    "lib/better_radar/client.rb",
    "lib/better_radar/version.rb",
    "spec/better_radar/client_spec.rb",
    "spec/fixtures/vcr_cassettes/fixtures_feed.yml",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/dmgarland/better_radar"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.2"
  s.summary = "A Ruby client for the BetRadar API"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<nokogiri>, [">= 0"])
    else
      s.add_dependency(%q<nokogiri>, [">= 0"])
    end
  else
    s.add_dependency(%q<nokogiri>, [">= 0"])
  end
end

