# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: better_radar 0.0.3 ruby lib

Gem::Specification.new do |s|
  s.name = "better_radar"
  s.version = "0.0.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Dan Garland, Kristian Knevitt, Joe Dickinson"]
  s.date = "2015-11-24"
  s.description = "SAX Parser that allows you to respond to information in the BetRadar XML feed"
  s.email = "dan@dangarland.co.uk"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".floo",
    ".flooignore",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "better_radar.gemspec",
    "lib/better_radar.rb",
    "lib/better_radar/client.rb",
    "lib/better_radar/configuration.rb",
    "lib/better_radar/document.rb",
    "lib/better_radar/element/base.rb",
    "lib/better_radar/element/bet.rb",
    "lib/better_radar/element/bet_probability.rb",
    "lib/better_radar/element/bet_result.rb",
    "lib/better_radar/element/card.rb",
    "lib/better_radar/element/categorical_information.rb",
    "lib/better_radar/element/category.rb",
    "lib/better_radar/element/competitor.rb",
    "lib/better_radar/element/entity.rb",
    "lib/better_radar/element/factory.rb",
    "lib/better_radar/element/goal.rb",
    "lib/better_radar/element/match.rb",
    "lib/better_radar/element/odds.rb",
    "lib/better_radar/element/outright.rb",
    "lib/better_radar/element/player.rb",
    "lib/better_radar/element/round.rb",
    "lib/better_radar/element/sport.rb",
    "lib/better_radar/element/storable.rb",
    "lib/better_radar/element/tournament.rb",
    "lib/better_radar/logger.rb",
    "lib/better_radar/parser.rb",
    "lib/better_radar/version.rb",
    "spec/better_radar/base_spec.rb",
    "spec/better_radar/better_radar_spec.rb",
    "spec/better_radar/categorical_information_spec.rb",
    "spec/better_radar/client_spec.rb",
    "spec/better_radar/configuration_spec.rb",
    "spec/better_radar/document_spec.rb",
    "spec/better_radar/entity_spec.rb",
    "spec/better_radar/match_spec.rb",
    "spec/better_radar/parser_spec.rb",
    "spec/fixtures/example_feed.xml",
    "spec/fixtures/example_feed2.xml",
    "spec/fixtures/example_feed3.xml",
    "spec/fixtures/sample_category.xml",
    "spec/fixtures/sample_match.xml",
    "spec/fixtures/sample_outright.xml",
    "spec/fixtures/sample_sport.xml",
    "spec/fixtures/sample_tournament.xml",
    "spec/fixtures/vcr_cassettes/fixtures_feed.yml",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/dmgarland/better_radar"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.4.3"
  s.summary = "A Ruby client for the BetRadar API"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<nokogiri>, [">= 0"])
      # s.add_runtime_dependency(%q<better_radar>, [">= 0"])
    else
      s.add_dependency(%q<nokogiri>, [">= 0"])
      # s.add_dependency(%q<better_radar>, [">= 0"])
    end
  else
    s.add_dependency(%q<nokogiri>, [">= 0"])
    # s.add_dependency(%q<better_radar>, [">= 0"])
  end
end

